### ISSUE TITLE
Open Requirements

### ISSUE THREAD

**Issue by RodrigoMattosoSilveira** [abraham/nutmeg-cli#3]
Hi - I would love to contribute, but I'm shy of doing so without more details as to the requirements. Let me know if you want to chat about it.

Regards
Rodrigo

**Comment by abraham** [comment]
There are no specific requirements to contributing to Nutmeg. The generally approach should look like this:

1. Identify something to add or improve
1. Open a new issue to explain the change and why it should be made
1. Discuss or get 👍  from a team member
1. Start implementing or ask for guidance if it's unfamiliar territory.

Please let me know if you have any additional questions.

**Comment by RodrigoMattosoSilveira** [comment]
I do have a REALLY dumb question ... how does the _nutmeg-cli_ build process builds the _bin_ folder?

**Comment by abraham** [comment]
the `bin` folder is static and doesn't change. It is part of the [NPM API](https://docs.npmjs.com/files/package.json#bin) for building CLIs.

This following snippet tells NPM to register `nutmeg` and `nutmeg-new` as programs the user can interact with. `nutmeg-new` is supposed to be called directly, instead `nutmeg` will forward commands with `new` to it transparently.

package.json file:
```json
{
  "bin": {
    "nutmeg": "bin/nutmeg",
    "nutmeg-new": "bin/nutmeg-new"
  },
}
```

Than Node takes over and handles executing the code described in `nutmeg-new`. This file just loads whatever is in the `dist/new.js` file and executes it.

nutmeg-new file:
```bash
#!/usr/bin/env node

require('../dist/new');
```
Files in the `dist` directory are generated with Webpack from files in the `src` directory.

I've added a developer guide that explains more of the process. Please let me know if any of it doesn't make sense.

https://github.com/abraham/nutmeg-cli/blob/master/DEVELOPER.md

**Comment by RodrigoMattosoSilveira** [comment]
Thanks
